# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WteUS_XtbbOTu0ForaGKoyCf6WlGuf9J
"""

from alpha_vantage.timeseries import TimeSeries
import pandas as pd

api_key = "RV4CZ54LIN34ZOP0"
ts = TimeSeries(key=api_key, output_format='pandas')

try:
    data, meta_data = ts.get_daily(symbol='RELIANCE.BSE', outputsize='compact')
    print("\n📊 Last 5 Days Data:\n")
    print(data.head())
except Exception as e:
    print("\n❌ Error fetching data:")
    print(e)